

CREATE ROLE SYSADMIN_ROLE;
GRANT CREATE SESSION TO SYSADMIN_ROLE;
GRANT EXECUTE ANY PROCEDURE TO SYSADMIN_ROLE;
GRANT CREATE sequence TO SYSADMIN_ROLE;
grant execute on SetCarSaleAvailability to SYSADMIN_ROLE;
grant execute on GetCurrentWorker to SYSADMIN_ROLE;
grant execute on GetClients to SYSADMIN_ROLE;


/

CREATE ROLE CLIENT_ROLE;
GRANT CREATE SESSION TO CLIENT_ROLE;
grant EXECUTE on GetCars to CLIENT_ROLE;
grant EXECUTE on GetCarsSearch to CLIENT_ROLE;
grant EXECUTE on GetSalesmen to CLIENT_ROLE;
grant EXECUTE on AddOrder to CLIENT_ROLE;
grant execute on SetCarSaleAvailability to CLIENT_ROLE;

grant execute on sys.dbms_crypto to CLIENT_ROLE;
grant execute on encode to CLIENT_ROLE;
grant execute on decode_val to CLIENT_ROLE;

commit;



/

select * from dba_SYS_PRIVS where GRANTEE='SYSADMIN_ROLE';



CREATE PROFILE CANYPERSON_BASE_PROFILE LIMIT
  PASSWORD_LIFE_TIME 180
  FAILED_LOGIN_ATTEMPTS 5
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME DEFAULT
  CONNECT_TIME 180
  IDLE_TIME 30;

/
COMMIT; 


CREATE USER SYSADMIN IDENTIFIED BY SYSADMINPASSWORD
  PROFILE CANYPERSON_BASE_PROFILE
  account unlock;
GRANT SYSADMIN_ROLE TO SYSADMIN;

/


CREATE USER SHOP_CLIENT IDENTIFIED BY CLIENTPASSWORD
  PROFILE CANYPERSON_BASE_PROFILE
  account unlock;
GRANT CLIENT_ROLE TO SHOP_CLIENT;

/

drop user SYSADMIN;
drop profile CANYPERSON_BASE_PROFILE;
drop role SYSADMIN_ROLE;
drop user SHOP_CLIENT;
drop user SYSADMIN;